#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2026  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. ${rc_functions}

PIDFILE="/var/run/knot-resolver.pid"

case "${1}" in
	start)
		# Increase the number of open file descriptors
		ulimit -n 524288

		boot_mesg "Starting Knot Resolver Daemon..."
		loadproc -u knot-resolver -b -f \
			/usr/bin/knot-resolver \
				-c /etc/knot-resolver/config.yaml
		;;

	stop)
		boot_mesg "Stopping Knot Resolver Daemon..."
		killproc /usr/bin/knot-resolver
		;;

	reload)
		/usr/bin/kresctl \
			--config=/etc/knot-resolver/config.yaml reload
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /usr/bin/knot-resolver
		;;

	*)
		echo "Usage: ${0} {start|stop|reload|restart|status}"
		exit 1
		;;
esac
