#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
# Copyright (C) 2024-2025  BPFire <vincent.mc.li@gmail.com>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. $rc_functions

eval $(/usr/local/bin/readhash /var/ipfire/loxilb/settings)

case "$1" in
	start)
		boot_mesg -n "Starting loxilb..."
		if [ "$ENABLE_LOXILB" == "on" ]; then
			if [ -d /opt/loxilb/dp/ ]; then
				umount /opt/loxilb/dp/
				rm -fr /opt/loxilb/dp/bpf
			fi

			mkdir -p /opt/loxilb/dp/
			mount -t bpf bpf /opt/loxilb/dp/

			#enable egress firewall SNAT for green network
			redip=$(< /var/ipfire/red/local-ipaddress)
			sed -i "s/\"REDIP\"/\"$redip\"/" /var/ipfire/loxilb/FWconfig.txt

			loadproc -b loxilb --config-path="/var/ipfire/loxilb/" --blacklist="eth[0-9]"
		fi
		;;

	stop)
		boot_mesg "Stopping loxilb..."
		if [ "$ENABLE_LOXILB" == "off" ]; then
			#remove egress firewall SNAT for green network
			loxicmd delete firewall --firewallRule="portName:green0"
			killproc loxilb
		fi
		;;

	status)
		statusproc /usr/bin/loxilb
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
