#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

if [ -n "$1" ]; then
	/usr/bin/ntpdate -su $1 $2
	ntpdatetest=$?

	if [ "$ntpdatetest" -eq 0 ]; then
		date "+%X %Z, %Y-%m-%d" > /var/lock/time/lastset

		/sbin/hwclock --systohc
		rm -f /var/lock/time/settimenow
		# reset counter variable
		cp /var/ipfire/time/counter.conf /var/lock/time/counter
	else
		logger -t ipfire "ntpdate error"
	fi

	exit ${ntpdatetest}
else
	echo Missing parameter
fi

exit 0
